Merge cnn-vis
uclaacm/no-filter pull request #18
Opened 2020-09-17 05:07 UTC by NishaMcNealis

2020-09-17 05:17 UTC, malsf21 requested changes

2020-09-17 05:17 UTC, malsf21 commented on package.json
> +    "react-scripts": "^3.4.3"
this should be a `"^3.4.3",` <--- with the comma, do you mind changing that quickly?

2020-09-17 19:19 UTC, malsf21 approved these changes
Hm, so I don't have any code feedback to give (everything seems relatively fine here), but I can't say I'm a huge fan of the magnifier: personally I don't think it helps zoom in on the image that much, especially since it isn't a super high-fidelity image anyways. I think a better solution would to create/design a better diagram that's more responsive, possibly by splitting up the stages. We could also code components that do the arrows/steps if needed.

That being said, I don't want this to be a blocker for extra content. And, in terms of body content too, we'll review that later w/ Arjun. I think for now, it's good to merge, though I'd like to remove the magnifier and create a better solution soon.

2020-09-18 07:19 UTC, NishaMcNealis commented
Definitely understand your concerns with the magnifier - I'm gonna go ahead and merge this as is for now since Aman wants to open up another PR but we're meeting tomorrow to brainstorm ways to improve it! Our main reason for not splitting up the picture into stages that the user can click through was that we wanted this section to show how everything connects in one diagram. One alternative Aman thought of was having a small version of the image with a button that expands the image to occupy most of the screen. Another option would be to incorporate both the static image and the stages so the user can see each individual step and the whole picture. Let us know if you have any other suggestions and we'll keep you posted :)

2020-09-18 07:20 UTC, merged